### PR TITLE
feat: add Modulation Extraction

### PR DESCRIPTION
**Pull request by Yuan-ManX**

### CODE REVIEW

**Comment by flavioschneider** [comment]
Try to keep the quality high without diverging too much from audio generation

**Comment by faroit** [comment]
@flavioschneider @Yuan-ManX isn't this pretty far from audio generation?

**Comment by flavioschneider** [comment]
Yeah, looking at it again this shouldn't be part of audio generation papers. @Yuan-ManX I would also avoid adding repositories that don't have an associated paper, except if something novel was presented and there are samples when clicking the link – this should be the priority, I'd even reject papers that don't. Things that are related to audio generation are also fine, e.g. CLAP models, speech, ...

**Comment by Yuan-ManX** [comment]
I very much agree with your thoughts, keep going!

**Pull request merged**
